# Managed by Hydra

ckpt_path: null

logger:
  # https://pytorch-lightning.readthedocs.io/en/stable/extensions/generated/pytorch_lightning.loggers.WandbLogger.html
  _target_: pytorch_lightning.loggers.WandbLogger
  project: General
  name: run_1

  # https://pytorch-lightning.readthedocs.io/en/stable/api/pytorch_lightning.loggers.tensorboard.html
  #  _target_: pytorch_lightning.loggers.TensorBoardLogger
  #  default_hp_metric: False
  #  name: run_1


# https://pytorch-lightning.readthedocs.io/en/stable/common/trainer.html
trainer:
  accelerator: gpu
  devices: auto
  strategy: ddp
  num_nodes: 1
  max_epochs: 496
  num_sanity_val_steps: 20
  check_val_every_n_epoch: 8
  profiler: simple
  log_every_n_steps: 30


# https://pytorch-lightning.readthedocs.io/en/stable/api/pytorch_lightning.callbacks.ModelCheckpoint.html
checkpoint_monitor:
  monitor: "val_eval/AP"
  mode: max
  save_last: True
  save_top_k: 3
  every_n_epochs: ${model.trainer.check_val_every_n_epoch}


lr_decay:
  decay_start_epoch: 200
  decay_stop_epoch: 512


inference:
  split: val
  evaluate: True
  save_predictions: True
  output_dir: predictions
