# Managed by Hydra

defaults:
  - base

log:
  WandbLogger:
    project: HAIS
    name: ${model.model.experiment_name}
  TensorBoardLogger:
    name: HAIS

trainer:
  max_epochs: 512

model:
  module: HAIS
  experiment_name: run_1

  m: 32 # 16 or 32
  blocks: [1, 2, 3, 4, 5, 6, 7]
  cluster_blocks: [1, 2]
  block_reps: 2

  use_coord: True
  use_color: False
  use_multiview: True
  use_normal: True

  fg_thresh: 1
  bg_thresh: 0

  score_scale: 50  # the minimal voxel size is 2cm
  score_fullscale: 20

  use_checkpoint: # /home/eamonn/Research/pointgroup-minkowski/output/scannet/pointgroup/train/pointgroup-scannet-epoch=127.ckpt
  pretrained_path: #/local-scratch/qiruiw/research/pointgroup-minkowski/log/scannet/pointgroup/train/2021-09-18_01-04-52/ckp-00512.tar #/local-scratch/qiruiw/research/pointgroup-minkowski/log/scannet/pointgroup/train/2021-08-24_11-42-20/ckp-00480.tar
  pretrained_module: #[backbone] # [backbone, sem_seg, offset_net, score_net, score_linear]
  pretrained_module_path: #/local-scratch/qiruiw/research/dense-scanrefer/log/scannet/pointgroup/train/2021-02-10_01-53-53/pointgroup_default_scannet-000000480.pth
  freeze_module: [ ]
  freeze_backbone: False
  prepare_epochs: 100

  loss_weight: [1, 1, 1, 1, 1, 1]


  point_aggr_radius: 0.03
  cluster_shift_meanActive: 300

  cal_iou_based_on_mask_start_epoch: 200

  use_mask_filter_score_feature_start_epoch: 200
  mask_filter_score_feature_thre: 0.5

  using_set_aggr_in_training: False
  using_set_aggr_in_testing: True

  max_proposal_num: 200


  test:
    TEST_NMS_THRESH: 0.3
    TEST_SCORE_THRESH: 0.09
    TEST_NPOINT_THRESH: 100
    test_mask_score_thre: -0.5
