# Managed by Hydra

defaults:
  - base

log:
  WandbLogger:
    project: PointGroup
    name: ${model.experiment_name}
  TensorBoardLogger:
    name: PointGroup

trainer:
  max_epochs: 496

model:
  module: PointGroup
  experiment_name: run_1

  m: 16 # 16 or 32
  blocks: [1, 2, 3, 4, 5, 6, 7]
  cluster_blocks: [1, 2]
  block_reps: 2

  use_coord: True
  use_color: False
  use_multiview: True
  use_normal: True

  fg_thresh: 0.75
  bg_thresh: 0.25

  score_scale: 50  # the minimal voxel size is 2cm
  score_fullscale: 14

  use_checkpoint: # /home/eamonn/Research/pointgroup-minkowski/output/scannet/pointgroup/train/pointgroup-scannet-epoch=127.ckpt
  pretrained_path: #/local-scratch/qiruiw/research/pointgroup-minkowski/log/scannet/pointgroup/train/2021-09-18_01-04-52/ckp-00512.tar #/local-scratch/qiruiw/research/pointgroup-minkowski/log/scannet/pointgroup/train/2021-08-24_11-42-20/ckp-00480.tar
  pretrained_module: #[backbone] # [backbone, sem_seg, offset_net, score_net, score_linear]
  pretrained_module_path: #/local-scratch/qiruiw/research/dense-scanrefer/log/scannet/pointgroup/train/2021-02-10_01-53-53/pointgroup_default_scannet-000000480.pth
  freeze_module: [ ]
  freeze_backbone: False
  prepare_epochs: 128

  loss_weight: [1, 1, 1, 1, 1, 1]


  cluster:
    # point grouping
    cluster_radius: 0.03
    cluster_meanActive: 50
    cluster_shift_meanActive: 300
    cluster_npoint_thre: 50


  test:
    TEST_NMS_THRESH: 0.3
    TEST_SCORE_THRESH: 0.09
    TEST_NPOINT_THRESH: 100
