general:
  task: # train, test, eval
  manual_seed: 123
  dataset: scannet
  model: pointgroup
  solver: PointGroupSolver
  config: conf/pointgroup_scannet.yaml


data:
  module: lib.dataset
  dataset: ScanNet
  loader: scannet_loader
  
  data_root: dataset
  file_suffix: .pth

  split: 
  mini: 

  classes: 20
  ignore_label: -1 # ignored classes
  requires_gt_mask: False

  scale: 50   # voxel_size = 1 / scale, scale 50(2cm)
  batch_size: 4
  num_workers: 16
  full_scale: [128, 512]
  max_num_point: 250000
  mode: 4 # 4=mean

  transform:
    jitter: True #True
    flip: True #True
    rot: True #True
    
  requires_bbox: True


model:
  module: model
  classname: PointGroup
  
  input_channel: 3
  m: 16 # 16 or 32
  blocks: [1, 2, 3, 4, 5, 6, 7]
  cluster_blocks: [1, 2]
  block_residual: True
  block_reps: 2

  use_coords: True
  crop_bbox: True
  pred_bbox: False

  num_bbox_class: 18
  num_heading_bin: 1
  num_size_cluster: 18

  use_checkpoint: #2021-02-10_01-53-53 #2021-09-18_01-04-52 #2021-08-24_11-42-20 #2021-07-12_17-34-59
  resume_epoch: #480
  pretrained_path: /project/3dlg-hcvc/pointgroup-minkowski/pointgroup.tar #/local-scratch/qiruiw/research/pointgroup-minkowski/log/scannet/pointgroup/train/2021-09-18_01-04-52/ckp-00512.tar #/local-scratch/qiruiw/research/pointgroup-minkowski/log/scannet/pointgroup/train/2021-08-24_11-42-20/ckp-00480.tar
  pretrained_module: [] #[backbone, sem_seg, offset_net, score_net, score_linear]
  pretrained_module_path: #/local-scratch/qiruiw/research/dense-scanrefer/log/scannet/pointgroup/train/2021-02-10_01-53-53/pointgroup_default_scannet-000000480.pth
  freeze_module: []


train:
  epochs: 480

  optim: 
    classname: Adam # Adam or SGD
    lr: 0.002
    momentum: 0.9 # SGD
    weight_decay: 0.0001 # SGD
  
  step_epoch: 480 #384
  multiplier: 0.5
  save_freq: 16  # also eval_freq
  loss_weight: [1.0, 1.0, 1.0, 1.0, 1.0] # semantic_loss, offset_norm_loss, offset_dir_loss, score_loss, bbox_loss (if applies)

  fg_thresh: 0.75
  bg_thresh: 0.25

  score_scale: 50 # the minimal voxel size is 2cm
  score_fullscale: 14
  score_mode: 4 # mean


cluster:
  ### point grouping
  cluster_radius: 0.03
  cluster_meanActive: 50
  cluster_shift_meanActive: 300
  cluster_npoint_thre: 50

  prepare_epochs: 128
  freeze_backbone: False

test:
  test_epoch: 384
  test_seed: 567

  TEST_NMS_THRESH: 0.3
  TEST_SCORE_THRESH: 0.09
  TEST_NPOINT_THRESH: 100

  requires_visualize: True


evaluation:
  model_utils_module: data.scannet.model_util_scannet
  gt_class_name: NYU20_CLASS_NAME
  gt_class_idx: NYU20_CLASS_IDX

  task:
  use_model: #2021-08-24_11-42-20 #2021-06-21_00-37-44


log:
  use_console_log: True
  verbose: 1 #30
  meter_names:
    - iter_time
    - semantic_loss
    - offset_norm_loss
    - offset_dir_loss
    - score_loss
    - mask_ious
    - total_loss
  tb_names:
    - semantic_loss
    - offset_norm_loss
    - offset_dir_loss
    - score_loss
    - total_loss
  bbox_names:
    - center_loss
    - heading_cls_loss
    - heading_reg_loss
    - size_cls_loss
    - size_reg_loss
    - sem_cls_loss
    - bbox_loss
    - pred_crop_bbox_iou
    - crop_bbox_iou
    - pred_bbox_iou
