general:
  manual_seed: 123
  dataset: scannet
  model: softgroup
  output_root: output
  logger: Wandb

data:
  module: lib.dataset
  dataset: ScanNet
  loader: scannet_loader
  file_suffix: .pth


  classes: 20
  ignore_label: -1 # ignored classes
  ignore_classes: [0, 1]
  class_names: ['cabinet', 'bed', 'chair', 'sofa', 'table', 'door', 'window', 'bookshelf', 'picture',
               'counter', 'desk', 'curtain', 'refrigerator', 'shower curtain', 'toilet', 'sink',
               'bathtub', 'otherfurniture']

  scale: 50   # voxel_size = 1 / scale, scale 50(2cm)
  batch_size: 4
  num_workers: 4
  full_scale: [128, 512]
  max_num_point: 250000
  max_num_instance: 128
  mode: 4 # 4=mean

  augmentation:
    jitter_xyz: True
    flip: True
    rotation: True
    elastic: True
    jitter_rgb: True


model:
  name: softgroup
  module: model
  classname: SoftGroup
  
  # input_channel: 131 # multiview + normals
  m: 32 # 16 or 32
  blocks: [1, 2, 3, 4, 5, 6, 7]
  cluster_blocks: [1, 2]
  block_reps: 2

  use_coords: True
  use_color: True
  use_multiview: False
  use_normal: False
  crop_bbox: False
  pred_bbox: False

  use_checkpoint: # /localhome/yza440/Research/pointgroup-minkowski/output/scannet/softgroup/train/softgroup-scannet-epoch=127.ckpt
  pretrained_path: #/local-scratch/qiruiw/research/pointgroup-minkowski/log/scannet/pointgroup/train/2021-09-18_01-04-52/ckp-00512.tar #/local-scratch/qiruiw/research/pointgroup-minkowski/log/scannet/pointgroup/train/2021-08-24_11-42-20/ckp-00480.tar
  pretrained_module: #[backbone] # [backbone, sem_seg, offset_net, score_net, score_linear]
  pretrained_module_path: #/local-scratch/qiruiw/research/dense-scanrefer/log/scannet/pointgroup/train/2021-02-10_01-53-53/pointgroup_default_scannet-000000480.pth
  freeze_module: []
  freeze_backbone: False
  prepare_epochs: 128

  grouping_cfg:
    score_thr: 0.2
    radius: 0.04
    mean_active: 300
    class_numpoint_mean: [ -1., -1., 3917., 12056., 2303.,
                           8331., 3948., 3166., 5629., 11719.,
                           1003., 3317., 4912., 10221., 3889.,
                           4136., 2120., 945., 3967., 2589. ]
    npoint_thr: 0.05  # absolute if class_numpoint == -1, relative if class_numpoint != -1

  instance_voxel_cfg:
    scale: 50
    spatial_shape: 20
  train_cfg:
    max_proposal_num: 200
    pos_iou_thr: 0.5
  test_cfg:
    cls_score_thr: 0.001
    mask_score_thr: -0.5
    min_npoint: 100


train:
  epochs: 400 # 480
  num_sanity_val_steps: 20
  check_val_every_n_epoch: 8
  save_checkpoint_every_n_epochs: 8  # negative number n means to save the best n models
  monitor: val_accuracy/AP_50

  optim: 
    name: Adam # Adam, AdamW or SGD
    lr: 0.001
  
  loss_weight: [1, 1, 1, 1, 1, 1] # semantic_loss, offset_norm_loss, offset_dir_loss, score_loss, bbox_loss (if applies)

